version: '3'
services:
  rockylinux:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tauruspet-mirror
    restart: unless-stopped
    tty: true
    command: ["/bin/bash"]
    volumes:
      - ~/src/LVG/work/mr_transfer:/home/pydev/mr_transfer
    network-mode: "host"
